### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by wenbinyu-PU** [banghuazhao/swiftcomp-flutter#19]
Issues with the readme file: 

1. The three screenshots should be updated. 
2.  the usage part is not clear. 
1. **Select a Material:** Choose from the existing material database or add a new material.
_Most function does not have this._

2. **Input Parameters:** Enter the necessary parameters for your composite material.
_Different apps have different inputs._

3. **Calculate:** Press the calculate button to obtain results.
4. **View Results:** Provide detailed information on the composite's properties.
_No all functions have this. It is not clear what does this refer to._

**Comment by banghuazhao** [comment]
Thanks for reviewing the readme! I have updated the readme file in this commit 
https://github.com/banghuazhao/swiftcomp-flutter/commit/02f98ba31acff2cdf70d8555cc82dbb83d44084e
